# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ ubuntu, windows ]
        node-version: [12.x, 14.x, 16.x, 17.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile --non-interactive

    - name: Run linters
      run: yarn lint

    - name: Run tests
      run: yarn test
